//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNoNCC
    {
        public int IDNhaCungCap { get; set; }
        public long IDHoaDon { get; set; }
        public System.DateTime HanTra { get; set; }
        public long SoNo { get; set; }
        public long SoDu { get; set; }
    
        public virtual HoaDonNCC HoaDonNCC { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
