//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        public HangHoa()
        {
            this.ChiTietDatHangNCC = new HashSet<ChiTietDatHangNCC>();
            this.ChiTietHoaDonNCC = new HashSet<ChiTietHoaDonNCC>();
            this.ChiTietNhapHang = new HashSet<ChiTietNhapHang>();
            this.ChiTietXuatHang = new HashSet<ChiTietXuatHang>();
            this.ChiTietYeuCau = new HashSet<ChiTietYeuCau>();
        }
    
        public long IDHangHoa { get; set; }
        public int IDNhaCungCap { get; set; }
        public int IDDanhMuc { get; set; }
        public string TenHangHoa { get; set; }
        public long GiaBan { get; set; }
        public string DonViTinh { get; set; }
        public string MoTaHangHoa { get; set; }
        public bool DangKinhDoanh { get; set; }
        public long SoLuongHangHoa { get; set; }
    
        public virtual ICollection<ChiTietDatHangNCC> ChiTietDatHangNCC { get; set; }
        public virtual ICollection<ChiTietHoaDonNCC> ChiTietHoaDonNCC { get; set; }
        public virtual ICollection<ChiTietNhapHang> ChiTietNhapHang { get; set; }
        public virtual ICollection<ChiTietXuatHang> ChiTietXuatHang { get; set; }
        public virtual ICollection<ChiTietYeuCau> ChiTietYeuCau { get; set; }
        public virtual DanhMucHangHoa DanhMucHangHoa { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
