//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQLKhoEntities : DbContext
    {
        public DBQLKhoEntities()
            : base("name=DBQLKhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietDatHangNCC> ChiTietDatHangNCC { get; set; }
        public DbSet<ChiTietHoaDonNCC> ChiTietHoaDonNCC { get; set; }
        public DbSet<ChiTietNhapHang> ChiTietNhapHang { get; set; }
        public DbSet<ChiTietXuatHang> ChiTietXuatHang { get; set; }
        public DbSet<ChiTietYeuCau> ChiTietYeuCau { get; set; }
        public DbSet<DanhMucHangHoa> DanhMucHangHoa { get; set; }
        public DbSet<DonDatHangNCC> DonDatHangNCC { get; set; }
        public DbSet<HangHoa> HangHoa { get; set; }
        public DbSet<HoaDonNCC> HoaDonNCC { get; set; }
        public DbSet<LoaiThanhToan> LoaiThanhToan { get; set; }
        public DbSet<NguoiDung> NguoiDung { get; set; }
        public DbSet<NhaCungCap> NhaCungCap { get; set; }
        public DbSet<PhieuNhapHang> PhieuNhapHang { get; set; }
        public DbSet<PhieuXuatHang> PhieuXuatHang { get; set; }
        public DbSet<TinhTrang> TinhTrang { get; set; }
        public DbSet<ThanhToanNCC> ThanhToanNCC { get; set; }
        public DbSet<VaiTro> VaiTro { get; set; }
        public DbSet<YeuCauXuatHang> YeuCauXuatHang { get; set; }
        public DbSet<CongNoNCC> CongNoNCC { get; set; }
    }
}
