//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.DonDatHangNCC = new HashSet<DonDatHangNCC>();
            this.HangHoa = new HashSet<HangHoa>();
            this.CongNoNCC = new HashSet<CongNoNCC>();
            this.ThanhToanNCC = new HashSet<ThanhToanNCC>();
        }
    
        public int IDNhaCungCap { get; set; }
        public string TenNhaCungCap { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string IDTaiKhoan { get; set; }
        public System.DateTime NgayMoTK { get; set; }
        public string TenChuTK { get; set; }
        public string ChiTietTK { get; set; }
        public string ChiTietKhac { get; set; }
    
        public virtual ICollection<DonDatHangNCC> DonDatHangNCC { get; set; }
        public virtual ICollection<HangHoa> HangHoa { get; set; }
        public virtual ICollection<CongNoNCC> CongNoNCC { get; set; }
        public virtual ICollection<ThanhToanNCC> ThanhToanNCC { get; set; }
    }
}
