//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHang
    {
        public PhieuNhapHang()
        {
            this.ChiTietNhapHang = new HashSet<ChiTietNhapHang>();
        }
    
        public long IDPhieuNhap { get; set; }
        public int IDTinhTrang { get; set; }
        public string NguoiLap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietNhapHang> ChiTietNhapHang { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
