//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatHang
    {
        public PhieuXuatHang()
        {
            this.ChiTietXuatHang = new HashSet<ChiTietXuatHang>();
        }
    
        public long IDPhieuXuat { get; set; }
        public int IDTinhTrang { get; set; }
        public long IDYeuCau { get; set; }
        public string NguoiLap { get; set; }
        public System.DateTime NgayXuat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietXuatHang> ChiTietXuatHang { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
        public virtual YeuCauXuatHang YeuCauXuatHang { get; set; }
    }
}
