//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToanNCC
    {
        public long IDThanhToan { get; set; }
        public int IDNhaCungCap { get; set; }
        public long IDHoaDon { get; set; }
        public int IDLoaiThanhToan { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public long SoTien { get; set; }
        public string GhiChu { get; set; }
        public string ChiTietKhac { get; set; }
    
        public virtual HoaDonNCC HoaDonNCC { get; set; }
        public virtual LoaiThanhToan LoaiThanhToan { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
