//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaiTro
    {
        public VaiTro()
        {
            this.NguoiDung = new HashSet<NguoiDung>();
        }
    
        public int IDVaiTro { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<NguoiDung> NguoiDung { get; set; }
    }
}
