//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauXuatHang
    {
        public YeuCauXuatHang()
        {
            this.ChiTietYeuCau = new HashSet<ChiTietYeuCau>();
            this.PhieuXuatHang = new HashSet<PhieuXuatHang>();
        }
    
        public long IDYeuCau { get; set; }
        public int IDTinhTrang { get; set; }
        public string NguoiLap { get; set; }
        public System.DateTime NgayYeuCau { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietYeuCau> ChiTietYeuCau { get; set; }
        public virtual ICollection<PhieuXuatHang> PhieuXuatHang { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
